# Generated by Django 2.0.5 on 2018-07-07 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopnowapp', '0004_auto_20180707_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
