# Generated by Django 2.0.5 on 2018-07-09 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopnowapp', '0005_customer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='orders',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
