# Generated by Django 2.0.5 on 2018-07-15 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopnowapp', '0007_product_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='date_delivered',
            field=models.DateField(blank=True, null=True),
        ),
    ]
