# Generated by Django 2.0.5 on 2018-07-16 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopnowapp', '0008_auto_20180715_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='added_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
